language: node_js
node_js:
  - "7"
  
before_install:
  - cd BilparkApp

before_script:
  - npm install

install:
  npm install -g codecov

script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack:
    rooms:
      - bachelor-it2901:GvHs8vnnvxJB8Rfb78EuRnJ8#travis