language: node_js
node_js:
  - "7"
  
before_install:
  - cd BilparkApp

before_script:
  - npm install

script:
  - npm test

notifications:
  email: false
  slack:
    rooms:
      - bachelor-it2901:GvHs8vnnvxJB8Rfb78EuRnJ8#travis